spring.application.name=ratestaff

spring.datasource.url=jdbc:postgresql://localhost:5432/ratestaff
spring.datasource.username=postgres
spring.datasource.password=246813bn

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.application.name=ratestaff

spring.datasource.url=jdbc:postgresql://localhost:5432/ratestaff
spring.datasource.username=postgres
spring.datasource.password=246813bn

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true